services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - retro_video_game_exchange
    ports:
      - "8000:80"
    networks:
      - distributed_system

  retro_video_game_exchange:
    build:
      context: ./Retro-Video-Game-Exchange-RMM3-API-
      dockerfile: Dockerfile
    env_file:
      - ./Retro-Video-Game-Exchange-RMM3-API-/.env
    ports:
      - "8000"
    networks:
      - distributed_system

networks:
  distributed_system: